const Maths = require('./src/Maths/Maths.js')
const Averigua = require('./src/Averigua/Averigua.js')
const Color = require('./src/Color/Color.js')
const Music = require('./src/Music/music.js')
const Media = require('./src/Media/media.js')
const DOM = require('./src/DOM/dom.js')
const Data = require('./src/Data/data.js')
const Utils = require('./src/Utils/utils.js')

const nn = {
  popup: Media.popup,
  loadImage: Media.loadImage,
  filterImage: Media.filterImage,
  filterVideo: Media.filterVideo,
  askFor: Media.askFor,
  askForStream: Media.askForStream,
  askForCapture: Media.askForCapture,
  askForNotifications: Media.askForNotifications,
  askForClipboard: Media.askForClipboard,
  askForBluetooth: Media.askForBluetooth,
  askForUSB: Media.askForUSB,
  askForSerial: Media.askForSerial,
  askForMotion: Media.askForMotion,
  askForOrientation: Media.askForOrientation,
  askForGPS: Media.askForGPS,
  MIDI: Media.MIDI,
  hyper: Media.hyper,

  notes: Music.SEMITONE_TO_NOTE,
  modes: Music.MODES,
  chords: Music.CHORDS,
  noteToMidi: Music.noteToMidi,
  noteToFrequency: Music.noteToFrequency,
  midiToNote: Music.midiToNote,
  midiToFrequency: Music.midiToFrequency,
  frequencyToMidi: Music.frequencyToMidi,
  frequencyToNote: Music.frequencyToNote,
  randomMode: Music.randomMode,
  createScale: Music.createScale,
  createChord: Music.createChord,
  voiceChord: Music.voiceChord,
  rotateScale: Music.rotateScale,
  transposeScale: Music.transposeScale,
  stripOctave: Music.stripOctave,

  sleep: Utils.sleep,
  times: Utils.times,
  range: Utils.range,

  parse: Data.parse,
  serialize: Data.serialize,
  download: Data.download,
  upload: Data.upload,

  isBrowser: Averigua.isBrowser.bind(Averigua),
  isMobile: Averigua.isMobile.bind(Averigua),
  hasWebGL: Averigua.hasWebGL.bind(Averigua),
  hasWebVR: Averigua.hasWebVR.bind(Averigua),
  hasMIDI: Averigua.hasMIDI.bind(Averigua),
  hasTouch: Averigua.hasTouch.bind(Averigua),
  orientation: Averigua.orientation.bind(Averigua),
  screen: Averigua.screen.bind(Averigua),
  gpuInfo: Averigua.gpuInfo.bind(Averigua),
  browserInfo: Averigua.browserInfo.bind(Averigua),
  platformInfo: Averigua.platformInfo.bind(Averigua),
  audioSupport: Averigua.audioSupport.bind(Averigua),
  videoSupport: Averigua.videoSupport.bind(Averigua),
  storageSupport: Averigua.storageSupport.bind(Averigua),
  fontSupport: Averigua.fontSupport.bind(Averigua),
  language: Averigua.language.bind(Averigua),
  timeZone: Averigua.timeZone.bind(Averigua),
  hasWebAudio: Averigua.hasWebAudio.bind(Averigua),
  hasWebXR: Averigua.hasWebXR.bind(Averigua),
  hasMediaDevices: Averigua.hasMediaDevices.bind(Averigua),
  hasDeviceMotion: Averigua.hasDeviceMotion.bind(Averigua),
  hasDeviceOrientation: Averigua.hasDeviceOrientation.bind(Averigua),
  hasPointerLock: Averigua.hasPointerLock.bind(Averigua),
  hasGamepad: Averigua.hasGamepad.bind(Averigua),
  hasWebSerial: Averigua.hasWebSerial.bind(Averigua),
  hasWebUSB: Averigua.hasWebUSB.bind(Averigua),
  hasBluetooth: Averigua.hasBluetooth.bind(Averigua),
  hasSpeechRecognition: Averigua.hasSpeechRecognition.bind(Averigua),
  hasSpeechSynthesis: Averigua.hasSpeechSynthesis.bind(Averigua),
  hasWebAssembly: Averigua.hasWebAssembly.bind(Averigua),
  hasFullscreen: Averigua.hasFullscreen.bind(Averigua),

  norm: Maths.norm,
  clamp: Maths.clamp,
  lerp: Maths.lerp,
  _lerp: Maths._lerp,
  map: Maths.map,
  dist: Maths.dist,
  angleBtw: Maths.angleBtw,
  radToDeg: Maths.radToDeg,
  degToRad: Maths.degToRad,
  cartesianToPolar: Maths.cartesianToPolar,
  polarToCartesian: Maths.polarToCartesian,
  shuffle: Maths.shuffle,
  randomInt: Maths.randomInt,
  randomFloat: Maths.randomFloat,
  random: Maths.random.bind(Maths),
  perlin: Maths.perlin,
  ease: (type, t) => Maths[`ease${type}`](t),

  randomColor: Color.random.bind(Color),
  lerpColor: Color.lerpColor.bind(Color),
  colorGradient: Color.colorGradient.bind(Color),
  colorScheme: Color.scheme.bind(Color),
  toRGB: Color.toRGB.bind(Color),
  rgb: Color.rgb.bind(Color),
  toHSL: Color.toHSL.bind(Color),
  hsl: Color.hsl.bind(Color),
  toHex: Color.toHex.bind(Color),
  hex: Color.hex.bind(Color),
  isLight: Color.isLight.bind(Color),
  colorContrast: Color.contrast.bind(Color),
  contrast: Color.contrast.bind(Color),
  colorMatch: Color.match.bind(Color),
  match: Color.match.bind(Color),
  alpha2hex: Color.alpha2hex.bind(Color),
  hex2alpha: Color.hex2alpha.bind(Color),
  closestColor: Color.closestColor.bind(Color)
}

DOM.register(nn)
window.nn = nn
